services:
  activity:
    container_name: activitymonitor
    image: 'midniteactivitymonitor:latest'
    build:
      context: .
      dockerfile: ./docker/Dockerfile-dev
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - ./src:/app/src
    env_file:
      - docker/.env
